services:
  - type: web
    name: my-portfolio
    runtime: node
    repo: https://github.com/SunnySatya/Myportfolio.git
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: ADMIN_EMAIL
        sync: false
    buildCommand: npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    domains:
      - myportfolio.onrender.com
